apiVersion: v1
kind: Service
metadata:
   name: prometheus-service
spec:
  type: NodePort
  selector:
    app: prometheus  # Update this label to match your Prometheus deployment labels
  ports:
  - port: 8084
    targetPort: 8084
    nodePort: 30074  # Expose on a NodePort