apiVersion: apps/v1
kind: Deployment
metadata:
 name: prometheus-deployment
spec:
  replicas: 3  # Number of replicas
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: eminegura/random-number-generator:dk
        ports:
        - containerPort: 8081
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"
        volumeMounts:
        - name: log-volume
          mountPath: /var/log/random-generator
      volumes:
      - name: log-volume
        hostPath:
          path: /var/log/random-generator  # Path on the host node