apiVersion: v1
kind: Service
metadata:
  name: random-number-generator-project-service
spec:
  type: NodePort
  selector:
    app: random-number-generator-project
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 30080  # Expose on a NodePort